var suntech = {
	common: [
		{
			id: 0,
			field: "hdr",
			length: 1,
			type: "hex",
			nested: "telemetry",
		},
		{
			id: 1,
			field: "packetLength",
			length: 2,
			type: "int",
			nested: "telemetry",
		},
		{
			id: 2,
			field: "deviceName",
			length: 5,
			type: "hex",
		},
	],
	messages: {
		81: [
			{
				id: 0,
				field: "remportMap",
				length: 3,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 1,
				field: "model",
				length: 1,
				type: "int",
				nested: "attributes",
			},
			{
				id: 2,
				field: "firmwareVersion",
				length: 3,
				type: "bytes",
				join: ".",
				nested: "attributes",
			},
			{
				id: 3,
				field: "reportType",
				length: 1,
				type: "int",
				enum: "reportEnum",
				nested: "telemetry",
			},
			{
				id: 4,
				field: "date",
				length: 3,
				type: "bytes",
				join: "/",
				nested: "telemetry",
			},
			{
				id: 5,
				field: "time",
				length: 3,
				type: "bytes",
				join: ":",
				nested: "telemetry",
			},
			{
				id: 6,
				field: "cellId",
				length: 4,
				type: "hex",
				nested: "telemetry",
			},
			{
				id: 7,
				field: "mcc",
				length: 2,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 8,
				field: "mnc",
				length: 2,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 9,
				field: "lac",
				length: 2,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 10,
				field: "signalStrength",
				length: 1,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 11,
				field: "latitude",
				length: 4,
				type: "coords",
				nested: "telemetry",
			},
			{
				id: 12,
				field: "longitude",
				length: 4,
				type: "cords",
				nested: "telemetry",
			},
			{
				id: 13,
				field: "speedInKph",
				length: 2,
				type: "int",
				nested: "telemetry",
				multiplier: 0.01,
			},
			{
				id: 14,
				field: "headingInDegree",
				length: 2,
				type: "int",
				nested: "telemetry",
				multiplier: 0.01,
			},

			{
				id: 15,
				field: "satellitesInView",
				length: 1,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 16,
				field: "gpsFixStatus",
				length: 1,
				type: "int",
				enum: "gpsFixEnum",
				nested: "telemetry",
			},
			{
				id: 17,
				field: "inState",
				length: 1,
				type: "bin",
				nested: "telemetry",
			},
			{
				id: 18,
				field: "outState",
				length: 1,
				type: "bin",
				nested: "telemetry",
			},
			{
				id: 19,
				field: "currentMode",
				length: 1,
				type: "int",
				enum: "deviceModeEnum",
				nested: "telemetry",
			},
			{
				id: 20,
				field: "reportReason",
				length: 1,
				type: "int",
				enum: "reportReasonEnum",
				nested: "telemetry",
			},
			{
				id: 21,
				field: "messageSequenceNumber",
				length: 2,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 22,
				field: "reserved",
				length: 1,
				type: "int",
				nested: "telemetry",
			},
			{
				id: 23,
				field: "assingMap",
				length: 4,
				type: "int",
				nested: "telemetry",
			},
		],
	},
	enums: {
		modelsEnum: {},
		messagesEnum: {
			81: "STT",
			91: "ASTT",
			82: "ALT",
			92: "AALT",
			85: "TRV",
			95: "ATRV",
			86: "OTR",
			96: "AOTR",
			88: "OBD",
			89: "FTR",
			98: "AOBD",
			90: "PID",
			A0: "APID",
			"8A": "OVD",
			"9A": "AOVD",
		},
		reportEnum: {
			0: "stored",
			1: "realTime",
		},
		gpsFixEnum: {
			0: "noFix",
			1: "fixed",
		},
		deviceModeEnum: {
			0: "parked",
			1: "driving",
			2: "idling",
			3: "speeding",
			4: "towing",
			5: "deactivatedZone",
			7: "powerDisconnected",
			9: "carry",
		},
		reportReasonEnum: {
			0: "command",
			1: "time",
			2: "distance",
			3: "heading",
			4: "heartbeat",
		},
	},
};
